"""Trusted LAN gateway for remote clients connecting to loopback-only ComfyUI."""

import asyncio
import logging
import time
from dataclasses import dataclass
from collections import OrderedDict
from contextlib import asynccontextmanager

import aiohttp
from aiohttp import web
from yarl import URL

from server import PromptServer


LOG = logging.getLogger("ComfierUI-Companion")
GATEWAY_HOST = "0.0.0.0"
GATEWAY_PORT = 8147
BACKEND = "http://127.0.0.1:8188"
DISPLAY_TEST_VERSION = "0.4.28"
_registered = False
_runner = None

# Stage 1: host-side large data accelerator. These payloads are generated by
# ComfyUI on the host already; the gateway keeps hot copies so weak clients do
# not repeatedly trigger expensive inventory generation/transfer work.
DATA_CACHE_MAX_ITEM_BYTES = 128 * 1024 * 1024
DATA_CACHE_DEFAULT_TTL = 60.0
DATA_CACHE_MAX_BYTES = 192 * 1024 * 1024
DATA_CACHE_MAX_ENTRIES = 128
_data_cache = OrderedDict()
_data_cache_stripes = [asyncio.Lock() for _ in range(64)]
_sessions = {}
_cache_epoch = 0
_data_cache_stats = {"hits": 0, "misses": 0, "stores": 0, "bypasses": 0, "prewarmed": 0}


@dataclass
class _CacheEntry:
    body: bytes
    content_type: str
    stored_at: float
    ttl: float

    @property
    def age(self) -> float:
        return max(0.0, time.monotonic() - self.stored_at)

    @property
    def fresh(self) -> bool:
        return self.age < self.ttl


def _data_cache_ttl(path: str) -> float | None:
    # Exact and prefixed Comfy API routes, both legacy and /api aliases.
    normalized = path[4:] if path.startswith("/api/") else path
    if normalized == "/object_info" or normalized.startswith("/object_info/"):
        return 120.0
    if normalized == "/models" or normalized.startswith("/models/"):
        return 45.0
    if normalized == "/embeddings":
        return 60.0
    if normalized == "/features":
        return 300.0
    return None


def _data_cache_key(request: web.Request) -> str:
    path = request.rel_url.raw_path
    path = path[4:] if path.startswith('/api/') else path
    raw_query = request.rel_url.raw_query_string
    return path + (f"?{raw_query}" if raw_query else "")


def _store_cache(key, entry):
    for old, value in list(_data_cache.items()):
        if not value.fresh: _data_cache.pop(old, None)
    _data_cache.pop(key, None)
    if len(entry.body) > min(DATA_CACHE_MAX_ITEM_BYTES, DATA_CACHE_MAX_BYTES): return
    while _data_cache and (len(_data_cache) >= DATA_CACHE_MAX_ENTRIES or sum(len(v.body) for v in _data_cache.values()) + len(entry.body) > DATA_CACHE_MAX_BYTES):
        _data_cache.popitem(last=False)
    _data_cache[key] = entry


@asynccontextmanager
async def _session(auto_decompress=False):
    key = (asyncio.get_running_loop(), auto_decompress)
    session = _sessions.get(key)
    if session is None or session.closed:
        session = aiohttp.ClientSession(auto_decompress=auto_decompress, timeout=aiohttp.ClientTimeout(total=None, connect=10, sock_read=180), connector=aiohttp.TCPConnector(limit=32), cookie_jar=aiohttp.DummyCookieJar())
        _sessions[key] = session
    yield session


async def _cleanup_sessions(application):
    if application is not None:
        task = application.get('comfier_prewarm')
        if task:
            task.cancel()
            try: await task
            except asyncio.CancelledError: pass
    loop = asyncio.get_running_loop()
    for key, session in list(_sessions.items()):
        if key[0] is loop:
            await session.close()
            _sessions.pop(key, None)


def _cache_headers(entry: _CacheEntry, state: str) -> dict[str, str]:
    return {
        "Content-Type": entry.content_type or "application/json",
        "Cache-Control": "private, max-age=15, stale-while-revalidate=60",
        "X-ComfierUI-Host-Data-Cache": state,
        "X-ComfierUI-Host-Data-Age-Ms": str(int(entry.age * 1000)),
    }


def invalidate_data_cache(prefix: str | None = None) -> None:
    global _cache_epoch
    _cache_epoch += 1
    if prefix is None:
        _data_cache.clear()
        return
    for key in list(_data_cache):
        path = key.split("?", 1)[0]
        normalized = path[4:] if path.startswith("/api/") else path
        if normalized.startswith(prefix):
            _data_cache.pop(key, None)

HOP_HEADERS = {
    "connection",
    "content-length",
    "host",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
    # A proxy WebSocket client must create its own upstream handshake. Reusing
    # the downstream browser's key/version/extensions can prevent ComfyUI from
    # establishing the session that supplies the frontend clientId.
    "sec-websocket-key",
    "sec-websocket-version",
    "sec-websocket-extensions",
    "sec-websocket-protocol",
    "sec-websocket-accept",
}


def _forward_headers(headers) -> dict[str, str]:
    return {key: value for key, value in headers.items() if key.lower() not in HOP_HEADERS}


def _backend_request_headers(headers) -> dict[str, str]:
    """Make proxied browser requests same-origin from ComfyUI's perspective."""
    forwarded = _forward_headers(headers)
    # HTML is transformed by the gateway, so request an identity body for
    # document navigations. Other assets retain their normal encoding.
    if "text/html" in headers.get("Accept", ""):
        forwarded["Accept-Encoding"] = "identity"
    if "Origin" in forwarded:
        forwarded["Origin"] = BACKEND
    if "Referer" in forwarded:
        forwarded["Referer"] = BACKEND + "/"
    return forwarded


def _backend_url(request: web.Request) -> URL:
    """Preserve encoded workflow paths such as workflows%2Fname.json."""
    raw_path = request.rel_url.raw_path
    raw_query = request.rel_url.raw_query_string
    target = BACKEND + raw_path + (f"?{raw_query}" if raw_query else "")
    return URL(target, encoded=True)


def _preprocess_html(payload: bytes) -> bytes:
    """Stamp/preload Companion Pre-Processor before the document reaches WebView."""
    try:
        html = payload.decode("utf-8")
    except UnicodeDecodeError:
        return payload
    if "__comfierHostPreprocessed" in html:
        return payload
    stamp = (
        '<meta name="comfierui-companion-display" content="' + DISPLAY_TEST_VERSION + '">'
        '<meta name="comfierui-stage1-data" content="host-cache-prewarm-v1"><meta name="comfierui-stage2-data" content="parsed-response-broker-v1"><meta name="comfierui-stage3-metadata" content="host-metadata-catalog-v1">'
        '<link rel="modulepreload" href="/comfierui/display-assets/comfierui_display_runtime.js?v=' + DISPLAY_TEST_VERSION + '">'
        '<link rel="modulepreload" href="/comfierui/display-assets/comfierui_display_bundle.js?v=' + DISPLAY_TEST_VERSION + '">'
    )
    marker = "</head>"
    if marker in html:
        html = html.replace(marker, stamp + marker, 1)
    else:
        html = stamp + html
    return html.encode("utf-8")


async def _relay_websocket(request: web.Request) -> web.WebSocketResponse:
    downstream = web.WebSocketResponse(heartbeat=25.0, max_msg_size=0)
    await downstream.prepare(request)
    target = _backend_url(request)

    async with aiohttp.ClientSession() as session:
        try:
            async with session.ws_connect(
                target,
                headers=_backend_request_headers(request.headers),
                heartbeat=25.0,
                max_msg_size=0,
            ) as upstream:
                async def client_to_comfy() -> None:
                    async for message in downstream:
                        if message.type == aiohttp.WSMsgType.TEXT:
                            await upstream.send_str(message.data)
                        elif message.type == aiohttp.WSMsgType.BINARY:
                            await upstream.send_bytes(message.data)
                        elif message.type in {aiohttp.WSMsgType.CLOSE, aiohttp.WSMsgType.ERROR}:
                            break

                async def comfy_to_client() -> None:
                    async for message in upstream:
                        if message.type == aiohttp.WSMsgType.TEXT:
                            await downstream.send_str(message.data)
                        elif message.type == aiohttp.WSMsgType.BINARY:
                            await downstream.send_bytes(message.data)
                        elif message.type in {aiohttp.WSMsgType.CLOSE, aiohttp.WSMsgType.ERROR}:
                            break

                tasks = [asyncio.create_task(client_to_comfy()), asyncio.create_task(comfy_to_client())]
                done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
                for task in pending:
                    task.cancel()
                await asyncio.gather(*pending, return_exceptions=True)
                for task in done:
                    task.result()
        except (aiohttp.ClientError, OSError) as error:
            LOG.warning("LAN gateway WebSocket relay failed: %s", error)
        finally:
            await downstream.close()
    return downstream


async def _fetch_cacheable(request: web.Request, target: URL, headers: dict[str, str], ttl: float) -> web.Response:
    key = _data_cache_key(request)
    entry = _data_cache.get(key)
    if entry is not None and entry.fresh:
        _data_cache_stats["hits"] += 1
        return web.Response(body=entry.body, status=200, headers=_cache_headers(entry, "HIT"))

    lock = _data_cache_stripes[hash(key) % len(_data_cache_stripes)]
    async with lock:
        entry = _data_cache.get(key)
        if entry is not None and entry.fresh:
            _data_cache_stats["hits"] += 1
            return web.Response(body=entry.body, status=200, headers=_cache_headers(entry, "HIT-AFTER-WAIT"))

        _data_cache_stats["misses"] += 1
        generation = _cache_epoch
        cache_headers = dict(headers)
        cache_headers["Accept-Encoding"] = "identity"
        async with _session(auto_decompress=True) as session:
            async with session.get(target, headers=cache_headers, allow_redirects=False, timeout=aiohttp.ClientTimeout(total=15)) as upstream:
                payload = await upstream.read()
                content_type = upstream.headers.get("Content-Type", "application/json")
                if upstream.status == 200 and len(payload) <= DATA_CACHE_MAX_ITEM_BYTES and not any(x in upstream.headers.get("Cache-Control", "").lower() for x in ("no-store", "no-cache", "private")):
                    entry = _CacheEntry(payload, content_type, time.monotonic(), ttl)
                    if generation == _cache_epoch: _store_cache(key, entry)
                    _data_cache_stats["stores"] += 1
                    return web.Response(
                        body=payload,
                        status=upstream.status,
                        reason=upstream.reason,
                        headers=_cache_headers(entry, "MISS-STORED"),
                    )
                _data_cache_stats["bypasses"] += 1
                response_headers = _forward_headers(upstream.headers)
                response_headers.pop("Content-Encoding", None)
                response_headers.pop("content-encoding", None)
                response_headers.pop("Content-Length", None)
                response_headers.pop("content-length", None)
                response_headers["X-ComfierUI-Host-Data-Cache"] = "BYPASS"
                return web.Response(body=payload, status=upstream.status, reason=upstream.reason, headers=response_headers)


async def _prewarm_one(path: str, ttl: float) -> None:
    async with _data_cache_stripes[hash(path) % len(_data_cache_stripes)]:
        await _prewarm_locked(path, ttl)


async def _prewarm_locked(path: str, ttl: float) -> None:
    key = path
    entry = _data_cache.get(key)
    if entry is not None and entry.fresh:
        return
    generation = _cache_epoch
    try:
        headers = {"Accept": "application/json", "Accept-Encoding": "identity"}
        async with _session(auto_decompress=True) as session:
            async with session.get(BACKEND + path, headers=headers, timeout=aiohttp.ClientTimeout(total=15)) as response:
                if response.status != 200:
                    return
                payload = await response.read()
                if len(payload) > DATA_CACHE_MAX_ITEM_BYTES:
                    return
                if generation != _cache_epoch: return
                _store_cache(key, _CacheEntry(
                    payload, response.headers.get("Content-Type", "application/json"), time.monotonic(), ttl
                ))
                _data_cache_stats["stores"] += 1
                _data_cache_stats["prewarmed"] += 1
    except (aiohttp.ClientError, OSError, asyncio.TimeoutError):
        return


async def _prewarm_data_cache() -> None:
    # Let Comfy finish startup first. This runs entirely on the host and never
    # blocks the gateway from accepting the Android/Web browser connection.
    await asyncio.sleep(1.0)
    paths = ("/features", "/models", "/embeddings", "/object_info")
    await asyncio.gather(*(_prewarm_one(path, _data_cache_ttl(path)) for path in paths))

    # Stage 3: build the model metadata catalog on the host before a weak
    # client opens model-heavy UI.  The root /models inventory is already hot;
    # warm each folder list so counts/search metadata can be answered without
    # client-driven enumeration.
    folders = _cached_json('/models')
    if isinstance(folders, list):
        semaphore = asyncio.Semaphore(4)
        async def warm_folder(folder):
            async with semaphore:
                path = '/models/' + str(folder)
                ttl = _data_cache_ttl(path)
                if ttl is not None: await _prewarm_one(path, ttl)
        await asyncio.gather(*(warm_folder(folder) for folder in folders))



def _query_int(request: web.Request, name: str, default: int, minimum: int, maximum: int) -> int:
    try:
        value = int(request.query.get(name, default))
    except (TypeError, ValueError):
        value = default
    return max(minimum, min(maximum, value))


def _cached_json(path: str):
    import json
    entry = _data_cache.get(path) or _data_cache.get('/api' + path)
    if entry is None or not entry.fresh:
        return None
    try:
        return json.loads(entry.body)
    except Exception:
        return None


def _search_nodes(request: web.Request) -> web.Response:
    q = request.query.get('q', '').strip().casefold()
    offset = _query_int(request, 'offset', 0, 0, 1000000)
    limit = _query_int(request, 'limit', 50, 1, 250)
    data = _cached_json('/object_info')
    if not isinstance(data, dict):
        return web.json_response({'ready': False, 'items': [], 'total': 0}, status=503)
    items = []
    for key, value in data.items():
        meta = value if isinstance(value, dict) else {}
        display = str(meta.get('display_name') or key)
        category = str(meta.get('category') or '')
        hay = (str(key) + '\n' + display + '\n' + category).casefold()
        if q and q not in hay:
            continue
        items.append({'name': str(key), 'display_name': display, 'category': category})
    items.sort(key=lambda x: (x['display_name'].casefold(), x['name'].casefold()))
    total = len(items)
    return web.json_response({'ready': True, 'query': q, 'offset': offset, 'limit': limit, 'total': total, 'items': items[offset:offset+limit]})


def _search_models(request: web.Request) -> web.Response:
    q = request.query.get('q', '').strip().casefold()
    folder = request.query.get('folder', '').strip()
    offset = _query_int(request, 'offset', 0, 0, 1000000)
    limit = _query_int(request, 'limit', 50, 1, 250)
    paths = []
    if folder:
        paths = [f'/models/{folder}']
    else:
        root = _cached_json('/models')
        if isinstance(root, list):
            paths = [f'/models/{str(x)}' for x in root]
    names = []
    for path in paths:
        data = _cached_json(path)
        if isinstance(data, list):
            names.extend({'folder': path.split('/models/',1)[1], 'name': str(x)} for x in data)
    if q:
        names = [x for x in names if q in x['name'].casefold() or q in x['folder'].casefold()]
    names.sort(key=lambda x: (x['folder'].casefold(), x['name'].casefold()))
    total = len(names)
    return web.json_response({'ready': True, 'query': q, 'folder': folder, 'offset': offset, 'limit': limit, 'total': total, 'items': names[offset:offset+limit]})

def _metadata_catalog() -> web.Response:
    """Compact host-computed metadata derived from Stage 1 inventories."""
    nodes = _cached_json('/object_info')
    model_folders = _cached_json('/models')
    category_counts: dict[str, int] = {}
    node_total = 0
    if isinstance(nodes, dict):
        node_total = len(nodes)
        for value in nodes.values():
            meta = value if isinstance(value, dict) else {}
            category = str(meta.get('category') or 'uncategorized')
            category_counts[category] = category_counts.get(category, 0) + 1

    model_counts: dict[str, int] = {}
    if isinstance(model_folders, list):
        for folder in model_folders:
            name = str(folder)
            data = _cached_json('/models/' + name)
            if isinstance(data, list):
                model_counts[name] = len(data)

    return web.json_response({
        'ready': isinstance(nodes, dict),
        'version': DISPLAY_TEST_VERSION,
        'nodes': {
            'total': node_total,
            'categories': dict(sorted(category_counts.items(), key=lambda x: x[0].casefold())),
        },
        'models': {
            'folders': model_counts,
            'total': sum(model_counts.values()),
        },
    })


def _cache_status() -> web.Response:
    now = time.monotonic()
    entries = []
    for key, entry in sorted(_data_cache.items()):
        entries.append({
            "key": key,
            "bytes": len(entry.body),
            "age_ms": int(max(0.0, now - entry.stored_at) * 1000),
            "ttl_ms": int(entry.ttl * 1000),
            "fresh": (now - entry.stored_at) < entry.ttl,
        })
    return web.json_response({
        "stage": "large-data-index-offload",
        "version": DISPLAY_TEST_VERSION,
        "stats": dict(_data_cache_stats),
        "entries": entries,
    })


async def _relay_http(request: web.Request) -> web.StreamResponse:
    if request.path == "/comfierui/data-cache/status":
        return _cache_status()
    if request.path == "/comfierui/metadata/catalog":
        return _metadata_catalog()
    if request.path == "/comfierui/search/nodes":
        return _search_nodes(request)
    if request.path == "/comfierui/search/models":
        return _search_models(request)
    if request.headers.get("Upgrade", "").lower() == "websocket":
        return await _relay_websocket(request)

    target = _backend_url(request)
    headers = _backend_request_headers(request.headers)
    if request.method == "GET" and not any(request.headers.get(h) for h in ("Authorization", "Range", "Cache-Control")):
        ttl = _data_cache_ttl(request.path)
        if ttl is not None:
            return await _fetch_cacheable(request, target, headers, ttl)
    # Do not attach a chunked request stream to bodyless requests.  In
    # particular, ComfyUI's workflow/user-data GET endpoints expect an ordinary
    # bodyless GET; forwarding an empty async iterator changes its wire shape
    # and can make those routes fail in WebView clients.
    body = await request.read() if request.can_read_body else None
    async with _session(auto_decompress=False) as session:
        try:
            async with session.request(
                request.method,
                target,
                headers=headers,
                data=body,
                allow_redirects=False,
            ) as upstream:
                response_headers = _forward_headers(upstream.headers)
                content_type = upstream.headers.get("Content-Type", "").lower()
                if request.method == "GET" and "text/html" in content_type:
                    payload = await upstream.read()
                    transformed = _preprocess_html(payload)
                    response_headers.pop("Content-Encoding", None)
                    response_headers.pop("content-encoding", None)
                    response_headers["Cache-Control"] = "no-store, no-cache, must-revalidate"
                    response_headers["X-ComfierUI-Display-Path"] = DISPLAY_TEST_VERSION
                    return web.Response(
                        body=transformed,
                        status=upstream.status,
                        reason=upstream.reason,
                        headers=response_headers,
                    )
                response = web.StreamResponse(
                    status=upstream.status,
                    reason=upstream.reason,
                    headers=response_headers,
                )
                await response.prepare(request)
                async for chunk in upstream.content.iter_chunked(1024 * 1024):
                    await response.write(chunk)
                await response.write_eof()
                return response
        except (aiohttp.ClientError, OSError) as error:
            raise web.HTTPBadGateway(text="Loopback ComfyUI is unavailable") from error


async def _start_gateway() -> None:
    global _runner
    application = web.Application(client_max_size=MAX_REQUEST_BYTES)
    application.on_cleanup.append(_cleanup_sessions)
    application.router.add_route("*", "/{path:.*}", _relay_http)
    runner = web.AppRunner(application, access_log=None)
    await runner.setup()
    try:
        await web.TCPSite(runner, GATEWAY_HOST, GATEWAY_PORT).start()
    except OSError as error:
        await runner.cleanup()
        LOG.error("LAN gateway could not bind %s:%d: %s", GATEWAY_HOST, GATEWAY_PORT, error)
        return
    _runner = runner
    application["comfier_prewarm"] = asyncio.create_task(_prewarm_data_cache())
    LOG.warning(
        "Companion LAN gateway listening on http://%s:%d -> %s (trusted LAN/tailnet only)",
        GATEWAY_HOST,
        GATEWAY_PORT,
        BACKEND,
    )


MAX_REQUEST_BYTES = 64 * 1024 * 1024


def register_companion_gateway() -> None:
    global _registered
    if _registered:
        return
    _registered = True
    PromptServer.instance.loop.create_task(_start_gateway())
