(()=>{
if(window.__comfierNodeSearchShell)return;
// Both loaders install the shared pre-focus guard before this visual shell.
if(!window.__comfierEditorGuard?.guardedHost)return;
const jobs=window.__comfierRuntime.scope("node-search");
const style=document.createElement('style');
style.id='comfier-node-search-shell-style';
style.textContent=`
.node-search-box-dialog-mask.comfier-node-search-shell{padding:0!important;align-items:flex-start!important;justify-content:flex-start!important}
.node-search-box-dialog-mask.comfier-node-search-shell>.invisible-dialog-root{display:block!important;position:fixed!important;left:var(--cm-search-left,12px)!important;top:var(--cm-search-top,12px)!important;width:var(--cm-search-width,min(768px,calc(100vw - 24px)))!important;height:var(--cm-search-height,auto)!important;min-width:0!important;min-height:0!important;max-width:none!important;max-height:none!important;margin:0!important;padding:6px!important;box-sizing:border-box!important;overflow:hidden!important;transform:none!important;border:1px solid var(--interface-stroke,var(--border-color,#3b4554))!important;border-radius:10px!important;background:var(--comfy-menu-bg,var(--p-content-background,#171717))!important;box-shadow:0 5px 18px rgba(0,0,0,.48)!important}
.node-search-box-dialog-mask.comfier-node-search-shell .comfy-vue-node-search-container{position:static!important;display:flex!important;width:100%!important;min-width:0!important;max-width:none!important;height:var(--cm-search-header-height,44px)!important;margin:0!important;padding:0!important;transform:none!important;align-items:stretch!important;justify-content:flex-start!important;gap:4px!important;box-sizing:border-box!important}
.node-search-box-dialog-mask.comfier-node-search-shell .comfy-vue-node-search-box{position:static!important;display:block!important;flex:1 1 auto!important;width:auto!important;min-width:0!important;max-width:none!important}
.node-search-box-dialog-mask.comfier-node-search-shell .comfy-vue-node-search-box>.p-autocomplete-input-multiple{width:100%!important;height:100%!important;min-width:0!important;box-sizing:border-box!important}
.node-search-box-dialog-mask.comfier-node-search-shell .comfy-vue-node-search-box>.p-autocomplete-overlay{display:block!important;position:absolute!important;left:6px!important;right:6px!important;top:calc(6px + var(--cm-search-header-height,44px) + 4px)!important;bottom:auto!important;width:auto!important;min-width:0!important;max-width:none!important;height:var(--cm-search-results-height,auto)!important;max-height:var(--cm-search-results-max,60vh)!important;margin:0!important;transform:none!important;box-sizing:border-box!important;overflow:hidden!important;border-radius:8px!important}
.node-search-box-dialog-mask.comfier-node-search-shell .p-autocomplete-list-container{width:100%!important;height:100%!important;max-height:100%!important;box-sizing:border-box!important;overflow-x:hidden!important;overflow-y:auto!important;overscroll-behavior:contain!important;-webkit-overflow-scrolling:touch!important;touch-action:pan-y!important;padding-bottom:10px!important}
@media (max-width:520px) and (orientation:portrait){
.node-search-box-dialog-mask.comfier-node-search-shell .p-autocomplete-list{padding:0!important}
.node-search-box-dialog-mask.comfier-node-search-shell .p-autocomplete-option{width:100%!important;height:auto!important;min-height:48px!important;padding:6px 8px!important;box-sizing:border-box!important;line-height:1.2!important;overflow:hidden!important}
.node-search-box-dialog-mask.comfier-node-search-shell .option-container{display:flex!important;width:100%!important;min-width:0!important;min-height:36px!important;align-items:center!important;justify-content:space-between!important;gap:8px!important;overflow:hidden!important}
.node-search-box-dialog-mask.comfier-node-search-shell .option-display-name{flex:1 1 auto!important;min-width:0!important;gap:2px!important;overflow:hidden!important}
.node-search-box-dialog-mask.comfier-node-search-shell .option-display-name>div{width:100%!important;min-width:0!important;height:auto!important;min-height:0!important;line-height:1.2!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}
.node-search-box-dialog-mask.comfier-node-search-shell .option-badges{display:flex!important;flex:0 1 38%!important;min-width:0!important;max-width:38%!important;align-items:center!important;justify-content:flex-end!important;overflow:hidden!important}
.node-search-box-dialog-mask.comfier-node-search-shell .option-badges .p-chip{display:inline-flex!important;width:auto!important;min-width:0!important;max-width:100%!important;height:28px!important;min-height:28px!important;padding:4px 8px!important;gap:4px!important;box-sizing:border-box!important;font-size:11px!important;line-height:1!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}
}`;
document.head.appendChild(style);
let current=null;
const viewport=()=>{const v=window.visualViewport;return{left:v?v.offsetLeft:0,top:v?v.offsetTop:0,width:v?v.width:innerWidth,height:v?v.height:innerHeight}};
function parts(){const mask=document.querySelector('.node-search-box-dialog-mask'),root=mask?.querySelector(':scope > .invisible-dialog-root'),header=root?.querySelector('.comfy-vue-node-search-container'),box=header?.querySelector('.comfy-vue-node-search-box'),input=box?.querySelector('input[id^="comfy-vue-node-search-box-input-"]'),panel=box?.querySelector(':scope > .p-autocomplete-overlay')||box?.querySelector('.p-autocomplete-overlay'),list=panel?.querySelector('.p-autocomplete-list-container');return mask&&root&&header&&box&&input?{mask,root,header,box,input,panel,list}:null}
function observe(p){if(window.ResizeObserver){p.ro=new ResizeObserver(schedule);p.ro.observe(p.header);if(p.panel)p.ro.observe(p.panel);if(p.list)p.ro.observe(p.list)}p.mo=window.__comfierMutations.create(schedule);p.mo.observe(p.root,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style']})}
function railBounds(){return window.__comfierUi.railBounds()}
function place(){const p=parts();if(!p){detach();return}if(!current||current.root!==p.root||current.input!==p.input){detach();current=p;p.mask.classList.add('comfier-node-search-shell');observe(p)}const v=viewport(),rail=railBounds(),edge=4,left=Math.max(v.left+edge,Math.ceil(rail?.right??v.left)+edge),right=v.left+v.width-edge,width=Math.max(120,Math.min(600,window.__comfierLayoutSide?.side()==='right'?(rail?.left??right)-v.left-edge*2:right-left)),top=Math.max(v.top+edge,Math.ceil(rail?.top??(v.top+edge))),bottom=Math.min(v.top+v.height-edge,Math.floor(rail?.bottom??(v.top+v.height-edge))),shellHeight=Math.max(120,bottom-top);p.mask.style.setProperty('--cm-search-left',(window.__comfierLayoutSide?.side()==='right'?Math.max(v.left+edge,Math.min(v.left+v.width-edge,rail?.left??(v.left+v.width))-edge-width):left)+'px');p.mask.style.setProperty('--cm-search-width',width+'px');const header=Math.max(42,Math.ceil(p.header.getBoundingClientRect().height));p.mask.style.setProperty('--cm-search-header-height',header+'px');const chrome=6+header+4+6,maxResults=Math.max(72,shellHeight-chrome);p.mask.style.setProperty('--cm-search-results-max',maxResults+'px');p.mask.style.setProperty('--cm-search-results-height',maxResults+'px');p.mask.style.setProperty('--cm-search-height',shellHeight+'px');p.mask.style.setProperty('--cm-search-top',top+'px');const free=window.__comfierLayoutEditor?.physicalSpace();if(free){p.mask.style.setProperty('--cm-search-left',free.left+'px');p.mask.style.setProperty('--cm-search-top',free.top+'px');p.mask.style.setProperty('--cm-search-width',Math.max(120,Math.min(width,free.right-free.left))+'px');p.mask.style.setProperty('--cm-search-height',Math.max(120,free.bottom-free.top)+'px');p.mask.style.setProperty('--cm-search-results-max',Math.max(72,free.bottom-free.top-chrome)+'px');p.mask.style.setProperty('--cm-search-results-height',Math.max(72,free.bottom-free.top-chrome)+'px')}}
function schedule(){jobs.frame('layout',place)}
function detach(){if(!current)return;current.ro?.disconnect();current.mo?.disconnect();current.mask.classList.remove('comfier-node-search-shell');['--cm-search-left','--cm-search-top','--cm-search-width','--cm-search-height','--cm-search-header-height','--cm-search-results-height','--cm-search-results-max'].forEach(n=>current.mask.style.removeProperty(n));current=null}
function visible(element){if(!element||!element.isConnected)return false;const rect=element.getBoundingClientRect(),computed=getComputedStyle(element);return rect.width>0&&rect.height>0&&computed.display!=='none'&&computed.visibility!=='hidden'}
function escape(target){const init={key:'Escape',code:'Escape',keyCode:27,which:27,bubbles:true,cancelable:true};for(const type of ['keydown','keyup']){try{(target||document).dispatchEvent(new KeyboardEvent(type,init))}catch(_){}}}
function closeNodeSearch(){const mask=document.querySelector('.node-search-box-dialog-mask:not(.p-overlay-mask-leave)');if(!visible(mask))return false;const overlays=[...document.querySelectorAll('.p-dialog-mask.p-overlay-mask:not(.node-search-box-dialog-mask):not(.p-overlay-mask-leave),.p-popover,.p-menu,.p-select-overlay,.p-multiselect-overlay,.p-cascadeselect-overlay')].filter(visible).map((element,index)=>({element,index,z:Number.parseInt(getComputedStyle(element).zIndex,10)||0})).sort((a,b)=>(window.__comfierLayers?.compare(b.element,a.element)||b.index-a.index));if(overlays.length){const top=overlays[0].element,backdrop=top.matches('.p-dialog-mask')?top:null,close=top.querySelector?.('[aria-label="Close"],[data-pc-section="closebutton"],.p-dialog-close-button');if(close)close.click();else if(backdrop)backdrop.click();else escape(top);return true}mask.click();setTimeout(()=>{if(visible(mask)&&!mask.classList.contains('p-overlay-mask-leave'))escape(mask)},0);return true}
const observer=window.__comfierMutations.create(records=>{if(current&&!current.root.isConnected){schedule();return}if(records.some(r=>r.target.closest?.('.node-search-box-dialog-mask')||[...r.addedNodes,...r.removedNodes].some(n=>n.nodeType===1&&(n.matches?.('.node-search-box-dialog-mask')||n.querySelector?.('.node-search-box-dialog-mask')))))schedule()});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('comfier-layout-editor-change',schedule);window.addEventListener('resize',schedule,{passive:true});window.addEventListener('orientationchange',schedule,{passive:true});if(window.visualViewport){visualViewport.addEventListener('resize',schedule,{passive:true});visualViewport.addEventListener('scroll',schedule,{passive:true})}
window.__comfierNodeSearchShell={handleBack:closeNodeSearch,remove(){if(!jobs.alive)return;jobs.dispose();detach();observer.disconnect();window.removeEventListener('comfier-layout-editor-change',schedule);window.removeEventListener('resize',schedule);window.removeEventListener('orientationchange',schedule);if(window.visualViewport){visualViewport.removeEventListener('resize',schedule);visualViewport.removeEventListener('scroll',schedule)}style.remove();delete window.__comfierNodeSearchShell}};
schedule();return'Unified responsive V1 node-search shell active in all views.';
})();
